add function node and valueType
jared-hughes/polygolf pull request #26
Opened 2022-11-10 07:56 UTC by MichalMarsalek

2022-11-10 08:06 UTC, MichalMarsalek commented
forgot to type check applications of user defined functions

2022-12-17 19:48 UTC, jared-hughes requested changes
Some nitpicks and a concern: contravariance of function parameters.

2022-12-17 19:48 UTC, jared-hughes commented on src/IR/exprs.ts
> +  isSafe: boolean; // whether both branches can be safely evaluated (allows for more golfing)
`isPure` makes more sense to me

2022-12-17 19:48 UTC, jared-hughes commented on src/IR/types.ts
> +        a.arguments.map((t, i) => union(t, b.arguments[i])),
Function types should be contravariant in the parameter types, so this should be `intersect`, not `union`. But it's more work to implement `intersect`, so you might want to just throw an error if the parameter types differ.

2022-12-18 07:10 UTC, merged